---
# AMD SMI Exporter
- name: Delete "amd-smi-exporter" metrics exporter Docker container
  community.docker.docker_container:
    name: amd-smi-exporter
    state: absent

- name: Delete "amd_smi_exporter_container" Docker image
  community.docker.docker_image:
    name: amd_smi_exporter_container
    tag: "0.1"
    state: absent

- name: Delete "amd_smi_exporter" installation artefacts
  ansible.builtin.file:
    path: /usr/local/src/amd_smi_exporter
    state: absent
  become: true

# GO AMD SMI Bindings
- name: Delete "go_amd_smi" installation artefacts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/src/go_amd_smi
    - /opt/goamdsmi
  become: true

- name: Clean Go Cache
  ansible.builtin.shell:
    cmd: "/usr/local/go/bin/go clean -modcache"

# E SMI LIB
- name: Remove "e_smi_lib64" debian package
  ansible.builtin.apt:
    name: e_smi_lib64
    state: absent
    autoremove: true
    purge: true
    update_cache: true
  become: true

- name: Delete "esmi_ib_library" installation artefacts
  ansible.builtin.file:
    path: /usr/local/src/esmi_ib_library
    state: absent
  become: true

# ROCM SMI LIB
- name: Remove
  ansible.builtin.shell:
    cmd: "amdgpu-install --uninstall --usecase=rocm"
  become: true

- name: Remove "amdgpu" debian package
  ansible.builtin.apt:
    name:
    - amdgpu
    state: absent
    autoremove: true
    purge: true
    update_cache: true
  become: true

- name: Delete "rocm_smi_lib" installation artefacts
  ansible.builtin.file:
    path: /usr/local/src/rocm_smi_lib
    state: absent
  become: true

# MSR-SAFE
- name: Delete groups "msr-user" and "msr-admin"
  ansible.builtin.group:
    group: "{{ item }}"
    state: absent
  loop:
    - msr-user
    - msr-admin
  become: true

- name: Unload "msr-safe" kernel module
  ansible.builtin.shell:
    cmd: rmmod msr-safe
  become: true

# TO DO REMOVE INSTALLATION ARTEFACTS FROM /lib/modules

- name: Delete "msr-safe" installation artefacts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/src/msr-safe
    - 
  become: true

- name: Update kernel module dependencies
  ansible.builtin.shell:
    cmd: depmod -A
  become: true

# AMD HSMP
- name: Unload "amd_hsmp" kernel module
  community.general.modprobe:
    name: amd_hsmp
    state: absent
  become: true

- name: Delete "amd_hsmp" installation artefacts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/src/amd_hsmp
    - "/usr/lib/modules/{{ ansible_kernel }}/updates/amd_hsmp.ko"
  become: true

- name: Update kernel module dependencies
  ansible.builtin.shell:
    cmd: depmod -A
  become: true