---
- name: Setup Mantis Shrimp Monitoring Stack
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Create mantis-shrimp Docker network
      community.docker.docker_network:
        name: mantis_shrimp
        driver: bridge
        internal: false
        scope: global
        state: present
  roles:
    - name: nvidia_dcgm
      tags:
        - exporter
    - name: cadvisor
      tags:
        - exporter
    - name: prometheus
    - name: grafana
    - name: traefik
      tags:
        - traefik

