---
- name: Teardown Mantis Shrimp Monitoring Stack
  hosts: all
  gather_facts: false
  tasks:
    - name: Teardown Prometheus server
      ansible.builtin.import_role:
        name: prometheus
        tasks_from: teardown
        
    - name: Teardown Nvidia DCGM metrics exporter
      ansible.builtin.import_role:
        name: nvidia_dcgm_exporter
        tasks_from: teardown

    - name: Mantis Shrimp Stack Artefacts
      ansible.builtin.file:
        path: /etc/mantis-shrimp
        state: absent
      become: true
