---
- name: Teardown Prometheus server
  hosts: prometheus_node
  gather_facts: false
  tasks:
    - name: Teardown Prometheus server
      ansible.builtin.import_role:
        name: prometheus
        tasks_from: teardown

- name: Remove Mantis Shrimp Stack Artefacts
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove artefact directory
      ansible.builtin.file:
        path: /etc/mantis-shrimp
        state: absent
      become: true