---
- name: Teardown Mantis Shrimp Monitoring Stack
  hosts: all
  gather_facts: false
  tasks:
    - name: Teardown Traefik reverse proxy
      ansible.builtin.import_role:
        name: traefik
        tasks_from: teardown
      tags:
        - traefik

    - name: Teardown Grafana server
      ansible.builtin.import_role:
        name: grafana
        tasks_from: teardown

    - name: Teardown Prometheus server
      ansible.builtin.import_role:
        name: prometheus
        tasks_from: teardown

    - name: Teardown node metrics exporter
      ansible.builtin.import_role:
        name: node_exporter
        tasks_from: teardown
      tags:
        - exporter
        
    - name: Teardown cAdvisor metrics exporter
      ansible.builtin.import_role:
        name: cadvisor
        tasks_from: teardown
      tags:
        - exporter
        - container-metrics
        
    - name: Teardown Nvidia DCGM metrics exporter
      ansible.builtin.import_role:
        name: nvidia_dcgm
        tasks_from: teardown
      tags:
        - exporter
        - gpu-metrics

    - name: Mantis Shrimp Stack Artefacts
      ansible.builtin.file:
        path: /etc/mantis-shrimp
        state: absent
      become: true

    - name: Remove mantis-shrimp Docker network
      community.docker.docker_network:
        name: mantis_shrimp
        state: absent
