---
- name: Add Nvidia Container Toolkit production repostory GPG key
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.asc
    mode: '0644'
    force: true
  become: true

- name: Add Nvidia Container Toolkit apt repository key
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.asc] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"
    filename: nvidia-container-toolkit
    state: present
  become: true

- name: Install Nvidia Container Toolkit apt package
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    update_cache: true
    state: latest
  become: true

- name: Configure Nvidia Container Toolkit for Docker runtime
  ansible.builtin.command:
    cmd: nvidia-ctk runtime configure --runtime=docker
  become: true

- name: Restart Docker Daemon
  ansible.builtin.systemd_service:
    name: docker
    daemon_reload: true
    state: restarted
  become: true

- name: Start Nvidia DCGM metrics exporter container
  community.docker.docker_container:
    name: nvidia-dcgm-exporter
    image: "{{ nvidia_dcgm__image }}:{{ nvidia_dcgm__image_tag }}"
    restart_policy: unless-stopped
    state: started
    networks:
      - name: mantis_shrimp
    # Will recreate any running Nvidia DCGM metrics exporter
    # container that doesn't match the expected version
    recreate: true
    restart: false
    device_requests: 
      - device_ids: 0
        driver: nvidia
        capabilities: 
          - gpu
          - compute
          - utility
